import { FormSchema } from '../types/form';

export const TEMPLATES: Record<string, FormSchema> = {
  employeeOnboarding: {
    id: 'schema_employee_onboarding',
    title: 'Employee Onboarding Form',
    description: 'Comprehensive onboarding form showcasing text, number fields, and multi-level nested groups.',
    version: '1.0.0',
    elements: [
      {
        id: 'f_emp_name',
        type: 'text',
        name: 'fullName',
        label: 'Full Legal Name',
        placeholder: 'e.g. Jane Doe',
        helperText: 'As it appears on government identification',
        defaultValue: 'Jane Doe',
        disabled: false,
        readOnly: false,
        validation: {
          required: true,
          requiredMessage: 'Full name is required',
          minLength: 3,
          minLengthMessage: 'Must be at least 3 characters',
          maxLength: 80,
        },
      },
      {
        id: 'f_emp_years',
        type: 'number',
        name: 'experienceYears',
        label: 'Years of Professional Experience',
        placeholder: 'e.g. 5',
        helperText: 'Total cumulative industry experience',
        defaultValue: 4,
        disabled: false,
        readOnly: false,
        validation: {
          required: true,
          requiredMessage: 'Experience years are required',
          min: 0,
          minMessage: 'Years cannot be negative',
          max: 60,
          maxMessage: 'Please enter a valid experience range',
        },
      },
      {
        id: 'g_contact',
        type: 'group',
        name: 'contactDetails',
        label: 'Contact Information',
        description: 'Primary communications and emergency contact channel',
        elements: [
          {
            id: 'f_email',
            type: 'text',
            name: 'workEmail',
            label: 'Company Email',
            placeholder: 'jane@company.com',
            helperText: 'Your designated work email address',
            defaultValue: 'jane@company.com',
            disabled: false,
            readOnly: false,
            validation: {
              required: true,
              requiredMessage: 'Work email is required',
            },
          },
          {
            id: 'f_ext_code',
            type: 'number',
            name: 'deskExtension',
            label: 'Desk Extension',
            placeholder: '4-digit internal code',
            helperText: 'Office telephony extension (1000 - 9999)',
            defaultValue: 4208,
            disabled: false,
            readOnly: false,
            validation: {
              required: false,
              min: 1000,
              minMessage: 'Extension must be at least 1000',
              max: 9999,
              maxMessage: 'Extension cannot exceed 9999',
            },
          },
          {
            id: 'g_emergency',
            type: 'group',
            name: 'emergencyContact',
            label: 'Emergency Point of Contact (Nested Group)',
            description: 'Designated next-of-kin or primary emergency contact',
            elements: [
              {
                id: 'f_emg_name',
                type: 'text',
                name: 'contactName',
                label: 'Emergency Contact Name',
                placeholder: 'e.g. Robert Doe',
                helperText: 'Full name of person to contact in emergency',
                defaultValue: 'Robert Doe',
                disabled: false,
                readOnly: false,
                validation: {
                  required: true,
                  requiredMessage: 'Emergency contact name is required',
                  minLength: 2,
                },
              },
              {
                id: 'f_emg_phone',
                type: 'text',
                name: 'phoneNumber',
                label: 'Emergency Contact Phone',
                placeholder: '+1 (555) 000-0000',
                helperText: 'Direct telephone number with area code',
                defaultValue: '+1 (555) 234-5678',
                disabled: false,
                readOnly: false,
                validation: {
                  required: true,
                  requiredMessage: 'Emergency contact phone is required',
                },
              },
              {
                id: 'f_emg_priority',
                type: 'number',
                name: 'callPriorityOrder',
                label: 'Notification Priority',
                placeholder: '1',
                helperText: '1 = First call, 2 = Secondary fallback',
                defaultValue: 1,
                disabled: false,
                readOnly: false,
                validation: {
                  required: true,
                  min: 1,
                  max: 5,
                },
              },
            ],
          },
        ],
      },
      {
        id: 'g_hardware',
        type: 'group',
        name: 'equipmentPreferences',
        label: 'Hardware & Workstation Setup',
        description: 'Physical equipment and display preferences',
        elements: [
          {
            id: 'f_preferred_os',
            type: 'text',
            name: 'preferredOperatingSystem',
            label: 'Target Operating System',
            placeholder: 'e.g. Linux, macOS, Windows',
            helperText: 'Primary engineering environment',
            defaultValue: 'macOS',
            disabled: false,
            readOnly: false,
            validation: {
              required: true,
              requiredMessage: 'Operating system preference is required',
            },
          },
          {
            id: 'f_monitor_count',
            type: 'number',
            name: 'requestedMonitors',
            label: 'External Monitors Required',
            placeholder: 'e.g. 2',
            helperText: 'Standard desk display allowance (0 to 4)',
            defaultValue: 2,
            disabled: false,
            readOnly: false,
            validation: {
              required: true,
              min: 0,
              max: 4,
            },
          },
        ],
      },
    ],
  },
  simpleFeedback: {
    id: 'schema_simple_feedback',
    title: 'Customer Feedback Form',
    description: 'A focused feedback questionnaire with text and number ratings.',
    version: '1.0.0',
    elements: [
      {
        id: 'f_client_name',
        type: 'text',
        name: 'customerName',
        label: 'Your Name or Company',
        placeholder: 'e.g. Acme Corp',
        defaultValue: '',
        disabled: false,
        readOnly: false,
        validation: {
          required: true,
          requiredMessage: 'Name is required',
        },
      },
      {
        id: 'f_rating',
        type: 'number',
        name: 'satisfactionScore',
        label: 'Overall Satisfaction (1 - 10)',
        placeholder: '10',
        helperText: '1 being lowest, 10 being highest',
        defaultValue: 9,
        disabled: false,
        readOnly: false,
        validation: {
          required: true,
          min: 1,
          max: 10,
        },
      },
      {
        id: 'f_comments',
        type: 'text',
        name: 'detailedFeedback',
        label: 'Detailed Feedback',
        placeholder: 'Tell us what went well and what we can improve...',
        defaultValue: '',
        disabled: false,
        readOnly: false,
        validation: {
          required: false,
          maxLength: 500,
        },
      },
    ],
  },
  blank: {
    id: 'schema_blank',
    title: 'Untitled Form',
    description: 'Configure new fields and nested groups using the toolbar.',
    version: '1.0.0',
    elements: [],
  },
};
